services:
  Cards:
    image: aniket8800/cards
    ports:
     - "8088:8088"
    networks:
     - example-network 
  Accounts:
    image: aniket8800/accounts
    ports:
     - "8084:8084"
    networks:
     - springboot-network   
  Insurance:
  	image:aniket8800/insurance
  	ports:
  	 - "9999:9999"  
  	networks:
  	 - bank-network  
networks:
  example-network: {}
  springboot-network: {}
  bank-network: {}
     